flowchart LR
  MISS0
    MISS0-->|GO TO|MISS1
  MISS1
    MISS1-->|GO TO|MISS2
  MISS2
    MISS2-->|GO TO|MISS2
    MISS2-->|GO TO|MISS3
  MISS3
    MISS3-->|GO TO|MISS4
  MISS4
    MISS4-->|GO TO|MISS5
  MISS5
    MISS5-->|GO TO|MISS6
  MISS6
    MISS6-->|GO TO|MISS7
  MISS7
    MISS7-->|GO TO|MISS8
  MISS8
    MISS8-->|GO TO|MISS9
    MISS8-->|GO TO|MISS8
  MISS9
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS21
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS10
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS10
    MISS9-->|GO TO|MISS13
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS13
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS17
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS17
    MISS9-->|GO TO|MISS9
  MISS10
    MISS10-->|GO TO|MISS11
  MISS11
    MISS11-->|GO TO|MISS12
  MISS12
    MISS12-->|GO TO|MISS12
    MISS12-->|GO TO|MISS9
    MISS12-->|GO TO|MISS21
  MISS13
    MISS13-->|GO TO|MISS14
  MISS14
    MISS14-->|GO TO|MISS15
  MISS15
    MISS15-->|GO TO|MISS16
  MISS16
    MISS16-->|GO TO|MISS16
    MISS16-->|GO TO|MISS9
    MISS16-->|GO TO|MISS21
  MISS17
    MISS17-->|GO TO|MISS18
  MISS18
    MISS18-->|GO TO|MISS19
  MISS19
    MISS19-->|GO TO|MISS20
  MISS20
    MISS20-->|GO TO|MISS20
    MISS20-->|GO TO|MISS9
    MISS20-->|GO TO|MISS21
  MISS21
    MISS21-->|GO TO|MISS22
  MISS22
    MISS22-->|GO TO|MISS23
  MISS23
    MISS23-->|GO TO|MISS24
  MISS24
    MISS24-->|GO TO|MISS24
    MISS24-->|GO TO|MISS25
  MISS25
    MISS25-->|GO TO|MISS26
  MISS26
    MISS26-->|GO TO|MISS27
  MISS27
    MISS27-->|GO TO|MISS27
    MISS27-->|GO TO|MISS28
    MISS27-->|GO TO|MISS28
    MISS27-->|GO TO|MISS28
  MISS28
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS39
    MISS28-->|GO TO|MISS29
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS29
    MISS28-->|GO TO|MISS32
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS32
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS36
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS36
    MISS28-->|GO TO|MISS28
  MISS29
    MISS29-->|GO TO|MISS30
  MISS30
    MISS30-->|GO TO|MISS31
  MISS31
    MISS31-->|GO TO|MISS31
    MISS31-->|GO TO|MISS28
    MISS31-->|GO TO|MISS39
  MISS32
    MISS32-->|GO TO|MISS33
  MISS33
    MISS33-->|GO TO|MISS34
  MISS34
    MISS34-->|GO TO|MISS35
  MISS35
    MISS35-->|GO TO|MISS35
    MISS35-->|GO TO|MISS28
    MISS35-->|GO TO|MISS39
  MISS36
    MISS36-->|GO TO|MISS37
  MISS37
    MISS37-->|GO TO|MISS38
  MISS38
    MISS38-->|GO TO|MISS38
    MISS38-->|GO TO|MISS28
    MISS38-->|GO TO|MISS39
  MISS39
    MISS39-->|GO TO|MISS40
  MISS40
    MISS40-->|GO TO|MISS41
  MISS41
    MISS41-->|GO TO|MISS41
    MISS41-->|GO TO|MISS42
    MISS41-->|GO TO|MISS42
  MISS42
    MISS42-->|GO TO|MISS43
  MISS43
    MISS43-->|GO TO|MISS44
  MISS44
    MISS44-->|GO TO|MISS45
  MISS45
    MISS45-->|GO TO|MISS46
  MISS46
    MISS46-->|GO TO|MISS47
  MISS47
    MISS47-->|GO TO|MISS48
  MISS48

  subgraph M0
    direction TB
    MISS0-->|FLY MISSION|FLY_0x00_0
  end
  subgraph M1
    direction TB
    MISS1-->|FLY MISSION|FLY_0x01_1
  end
  subgraph M2
    direction TB
    MISS2-->|FLY MISSION|FLY_0x02_2
  end
  subgraph M4
    direction TB
    MISS4-->|FLY MISSION|FLY_0x03_3
  end
  subgraph M6
    direction TB
    MISS6-->|FLY MISSION|FLY_0x04_4
  end
  subgraph M7
    direction TB
    MISS7-->|FLY MISSION|FLY_0x05_5
  end
  subgraph M8
    direction TB
    MISS8-->|FLY MISSION|FLY_0x06_6
  end
  subgraph M10
    direction TB
    MISS10-->|FLY MISSION|FLY_0x07_7
  end
  subgraph M11
    direction TB
    MISS11-->|FLY MISSION|FLY_0x08_8
  end
  subgraph M12
    direction TB
    MISS12-->|FLY MISSION|FLY_0x09_9
  end
  subgraph M14
    direction TB
    MISS14-->|FLY MISSION|FLY_0x0B_11
  end
  subgraph M15
    direction TB
    MISS15-->|FLY MISSION|FLY_0x0C_12
  end
  subgraph M16
    direction TB
    MISS16-->|FLY MISSION|FLY_0x0D_13
  end
  subgraph M17
    direction TB
    MISS17-->|FLY MISSION|FLY_0x0E_14
  end
  subgraph M18
    direction TB
    MISS18-->|FLY MISSION|FLY_0x0F_15
    MISS18-->|FLY MISSION|FLY_0x2B_43
  end
  subgraph M19
    direction TB
    MISS19-->|FLY MISSION|FLY_0x10_16
  end
  subgraph M20
    direction TB
    MISS20-->|FLY MISSION|FLY_0x11_17
  end
  subgraph M21
    direction TB
    MISS21-->|FLY MISSION|FLY_0x12_18
  end
  subgraph M22
    direction TB
    MISS22-->|FLY MISSION|FLY_0x13_19
  end
  subgraph M23
    direction TB
    MISS23-->|FLY MISSION|FLY_0x14_20
    MISS23-->|FLY MISSION|FLY_0x14_20
  end
  subgraph M24
    direction TB
    MISS24-->|FLY MISSION|FLY_0x15_21
  end
  subgraph M25
    direction TB
    MISS25-->|FLY MISSION|FLY_0x16_22
  end
  subgraph M26
    direction TB
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
  end
  subgraph M27
    direction TB
    MISS27-->|FLY MISSION|FLY_0x18_24
  end
  subgraph M29
    direction TB
    MISS29-->|FLY MISSION|FLY_0x19_25
  end
  subgraph M30
    direction TB
    MISS30-->|FLY MISSION|FLY_0x1A_26
  end
  subgraph M31
    direction TB
    MISS31-->|FLY MISSION|FLY_0x1B_27
  end
  subgraph M32
    direction TB
    MISS32-->|FLY MISSION|FLY_0x1C_28
  end
  subgraph M33
    direction TB
    MISS33-->|FLY MISSION|FLY_0x1D_29
    MISS33-->|FLY MISSION|FLY_0x2D_45
  end
  subgraph M34
    direction TB
    MISS34-->|FLY MISSION|FLY_0x1E_30
  end
  subgraph M35
    direction TB
    MISS35-->|FLY MISSION|FLY_0x1F_31
  end
  subgraph M36
    direction TB
    MISS36-->|FLY MISSION|FLY_0x20_32
  end
  subgraph M37
    direction TB
    MISS37-->|FLY MISSION|FLY_0x21_33
    MISS37-->|FLY MISSION|FLY_0x2E_46
  end
  subgraph M38
    direction TB
    MISS38-->|FLY MISSION|FLY_0x22_34
  end
  subgraph M40
    direction TB
    MISS40-->|FLY MISSION|FLY_0x23_35
  end
  subgraph M41
    direction TB
    MISS41-->|FLY MISSION|FLY_0x24_36
  end
  subgraph M42
    direction TB
    MISS42-->|FLY MISSION|FLY_0x25_37
  end
  subgraph M43
    direction TB
    MISS43-->|FLY MISSION|FLY_0x26_38
  end
  subgraph M44
    direction TB
    MISS44-->|FLY MISSION|FLY_0x27_39
  end
  subgraph CONV0
    MISS0-->|CONVERSATION|CONV_0x0C_12
    MISS0-->|CONVERSATION|CONV_0x0D_13
    MISS0-->|CONVERSATION|CONV_0x0E_14
    MISS0-->|CONVERSATION|CONV_0x1F_31
    MISS0-->|CONVERSATION|CONV_0x0B_11
    MISS0-->|CONVERSATION|CONV_0x0A_10
  end
  subgraph CONV1
    MISS1-->|CONVERSATION|CONV_0x11_17
    MISS1-->|CONVERSATION|CONV_0x12_18
    MISS1-->|CONVERSATION|CONV_0x0F_15
    MISS1-->|CONVERSATION|CONV_0x10_16
  end
  subgraph CONV2
    MISS2-->|CONVERSATION|CONV_0x17_23
    MISS2-->|CONVERSATION|CONV_0x18_24
    MISS2-->|CONVERSATION|CONV_0x14_20
    MISS2-->|CONVERSATION|CONV_0x16_22
    MISS2-->|CONVERSATION|CONV_0x13_19
    MISS2-->|CONVERSATION|CONV_0x15_21
    MISS2-->|CONVERSATION|CONV_0x19_25
    MISS2-->|CONVERSATION|CONV_0x1A_26
    MISS2-->|CONVERSATION|CONV_0x1B_27
    MISS2-->|CONVERSATION|CONV_0x1C_28
  end

  subgraph CONV4
    MISS4-->|CONVERSATION|CONV_0x1E_30
    MISS4-->|CONVERSATION|CONV_0x1D_29
    MISS4-->|CONVERSATION|CONV_0x2A_42
    MISS4-->|CONVERSATION|CONV_0x22_34
    MISS4-->|CONVERSATION|CONV_0x20_32
    MISS4-->|CONVERSATION|CONV_0x21_33
    MISS4-->|CONVERSATION|CONV_0xEB_235
    MISS4-->|CONVERSATION|CONV_0x24_36
    MISS4-->|CONVERSATION|CONV_0x25_37
  end

  subgraph CONV6
    MISS6-->|CONVERSATION|CONV_0x23_35
    MISS6-->|CONVERSATION|CONV_0x2C_44
    MISS6-->|CONVERSATION|CONV_0x28_40
    MISS6-->|CONVERSATION|CONV_0x26_38
    MISS6-->|CONVERSATION|CONV_0x2B_43
    MISS6-->|CONVERSATION|CONV_0x2D_45
    MISS6-->|CONVERSATION|CONV_0x29_41
    MISS6-->|CONVERSATION|CONV_0x27_39
  end
  subgraph CONV7
    MISS7-->|CONVERSATION|CONV_0x30_48
    MISS7-->|CONVERSATION|CONV_0x2E_46
    MISS7-->|CONVERSATION|CONV_0x31_49
  end
  subgraph CONV8
    MISS8-->|CONVERSATION|CONV_0x35_53
    MISS8-->|CONVERSATION|CONV_0x34_52
    MISS8-->|CONVERSATION|CONV_0x36_54
    MISS8-->|CONVERSATION|CONV_0x32_50
    MISS8-->|CONVERSATION|CONV_0x33_51
    MISS8-->|CONVERSATION|CONV_0x37_55
    MISS8-->|CONVERSATION|CONV_0x38_56
  end
  subgraph CONV9
    MISS9-->|CONVERSATION|CONV_0x45_69
    MISS9-->|CONVERSATION|CONV_0x46_70
    MISS9-->|CONVERSATION|CONV_0x39_57
    MISS9-->|CONVERSATION|CONV_0xE8_232
    MISS9-->|CONVERSATION|CONV_0x49_73
    MISS9-->|CONVERSATION|CONV_0xE5_229
    MISS9-->|CONVERSATION|CONV_0x5D_93
    MISS9-->|CONVERSATION|CONV_0xE6_230
    MISS9-->|CONVERSATION|CONV_0x70_112
    MISS9-->|CONVERSATION|CONV_0x71_113
    MISS9-->|CONVERSATION|CONV_0x01_1
    MISS9-->|CONVERSATION|CONV_0x00_0
    MISS9-->|CONVERSATION|CONV_0x58_88
    MISS9-->|CONVERSATION|CONV_0x59_89
    MISS9-->|CONVERSATION|CONV_0x5A_90
    MISS9-->|CONVERSATION|CONV_0x5B_91
    MISS9-->|CONVERSATION|CONV_0x6D_109
    MISS9-->|CONVERSATION|CONV_0x6E_110
    MISS9-->|CONVERSATION|CONV_0x3E_62
    MISS9-->|CONVERSATION|CONV_0x3F_63
    MISS9-->|CONVERSATION|CONV_0x40_64
    MISS9-->|CONVERSATION|CONV_0x06_6
    MISS9-->|CONVERSATION|CONV_0x4E_78
    MISS9-->|CONVERSATION|CONV_0x4F_79
    MISS9-->|CONVERSATION|CONV_0x50_80
    MISS9-->|CONVERSATION|CONV_0x07_7
    MISS9-->|CONVERSATION|CONV_0x62_98
    MISS9-->|CONVERSATION|CONV_0x63_99
    MISS9-->|CONVERSATION|CONV_0x64_100
    MISS9-->|CONVERSATION|CONV_0x04_4
    MISS9-->|CONVERSATION|CONV_0x02_2
  end
  subgraph CONV10
    MISS10-->|CONVERSATION|CONV_0x48_72
    MISS10-->|CONVERSATION|CONV_0x3B_59
    MISS10-->|CONVERSATION|CONV_0x3A_58
  end
  subgraph CONV11
    MISS11-->|CONVERSATION|CONV_0x41_65
    MISS11-->|CONVERSATION|CONV_0x3C_60
    MISS11-->|CONVERSATION|CONV_0x3D_61
  end
  subgraph CONV12
    MISS12-->|CONVERSATION|CONV_0x44_68
    MISS12-->|CONVERSATION|CONV_0x42_66
    MISS12-->|CONVERSATION|CONV_0x43_67
    MISS12-->|CONVERSATION|CONV_0x47_71
  end
  subgraph CONV13
    MISS13-->|CONVERSATION|CONV_0x4B_75
    MISS13-->|CONVERSATION|CONV_0x4A_74
    MISS13-->|CONVERSATION|CONV_0x5C_92
  end
  subgraph CONV14
    MISS14-->|CONVERSATION|CONV_0x53_83
    MISS14-->|CONVERSATION|CONV_0x51_81
    MISS14-->|CONVERSATION|CONV_0x4C_76
    MISS14-->|CONVERSATION|CONV_0x4D_77
  end
  subgraph CONV15
    MISS15-->|CONVERSATION|CONV_0x54_84
    MISS15-->|CONVERSATION|CONV_0x55_85
    MISS15-->|CONVERSATION|CONV_0x56_86
    MISS15-->|CONVERSATION|CONV_0x52_82
  end
  subgraph CONV16
    MISS16-->|CONVERSATION|CONV_0x57_87
  end
  subgraph CONV17
    MISS17-->|CONVERSATION|CONV_0x6F_111
    MISS17-->|CONVERSATION|CONV_0x5F_95
    MISS17-->|CONVERSATION|CONV_0x5E_94
  end
  subgraph CONV18
    MISS18-->|CONVERSATION|CONV_0x66_102
    MISS18-->|CONVERSATION|CONV_0x65_101
    MISS18-->|CONVERSATION|CONV_0x60_96
    MISS18-->|CONVERSATION|CONV_0x61_97
  end
  subgraph CONV19
    MISS19-->|CONVERSATION|CONV_0x69_105
    MISS19-->|CONVERSATION|CONV_0x67_103
    MISS19-->|CONVERSATION|CONV_0x68_104
    MISS19-->|CONVERSATION|CONV_0x67_103
    MISS19-->|CONVERSATION|CONV_0x68_104
  end
  subgraph CONV20
    MISS20-->|CONVERSATION|CONV_0x6A_106
    MISS20-->|CONVERSATION|CONV_0x6B_107
    MISS20-->|CONVERSATION|CONV_0x6C_108
  end
  subgraph CONV21
    MISS21-->|CONVERSATION|CONV_0x45_69
    MISS21-->|CONVERSATION|CONV_0x46_70
    MISS21-->|CONVERSATION|CONV_0x49_73
    MISS21-->|CONVERSATION|CONV_0xE4_228
    MISS21-->|CONVERSATION|CONV_0x5D_93
    MISS21-->|CONVERSATION|CONV_0xE6_230
    MISS21-->|CONVERSATION|CONV_0x70_112
    MISS21-->|CONVERSATION|CONV_0x71_113
    MISS21-->|CONVERSATION|CONV_0xE9_233
    MISS21-->|CONVERSATION|CONV_0x74_116
    MISS21-->|CONVERSATION|CONV_0x58_88
    MISS21-->|CONVERSATION|CONV_0x59_89
    MISS21-->|CONVERSATION|CONV_0x5A_90
    MISS21-->|CONVERSATION|CONV_0x5B_91
    MISS21-->|CONVERSATION|CONV_0x6D_109
    MISS21-->|CONVERSATION|CONV_0x6E_110
    MISS21-->|CONVERSATION|CONV_0x77_119
    MISS21-->|CONVERSATION|CONV_0x78_120
    MISS21-->|CONVERSATION|CONV_0x79_121
    MISS21-->|CONVERSATION|CONV_0x73_115
    MISS21-->|CONVERSATION|CONV_0x72_114
  end
  subgraph CONV22
    MISS22-->|CONVERSATION|CONV_0x75_117
    MISS22-->|CONVERSATION|CONV_0x76_118
    MISS22-->|CONVERSATION|CONV_0x7A_122
  end
  subgraph CONV23
    MISS23-->|CONVERSATION|CONV_0x7D_125
    MISS23-->|CONVERSATION|CONV_0x7C_124
    MISS23-->|CONVERSATION|CONV_0x7B_123
    MISS23-->|CONVERSATION|CONV_0x7E_126
    MISS23-->|CONVERSATION|CONV_0x7F_127
    MISS23-->|CONVERSATION|CONV_0x7F_127
  end
  subgraph CONV24
    MISS24-->|CONVERSATION|CONV_0x83_131
    MISS24-->|CONVERSATION|CONV_0x84_132
    MISS24-->|CONVERSATION|CONV_0x82_130
    MISS24-->|CONVERSATION|CONV_0x80_128
    MISS24-->|CONVERSATION|CONV_0x81_129
  end
  subgraph CONV25
    MISS25-->|CONVERSATION|CONV_0x85_133
    MISS25-->|CONVERSATION|CONV_0xE7_231
    MISS25-->|CONVERSATION|CONV_0xEA_234
    MISS25-->|CONVERSATION|CONV_0xE9_233
    MISS25-->|CONVERSATION|CONV_0x93_147
    MISS25-->|CONVERSATION|CONV_0x88_136
    MISS25-->|CONVERSATION|CONV_0x8A_138
    MISS25-->|CONVERSATION|CONV_0x8B_139
    MISS25-->|CONVERSATION|CONV_0x8C_140
    MISS25-->|CONVERSATION|CONV_0x89_137
    MISS25-->|CONVERSATION|CONV_0x87_135
    MISS25-->|CONVERSATION|CONV_0x86_134
  end
  subgraph CONV26
    MISS26-->|CONVERSATION|CONV_0x8D_141
    MISS26-->|CONVERSATION|CONV_0x8D_141
    MISS26-->|CONVERSATION|CONV_0x8D_141
  end
  subgraph CONV27
    MISS27-->|CONVERSATION|CONV_0x90_144
    MISS27-->|CONVERSATION|CONV_0x8E_142
    MISS27-->|CONVERSATION|CONV_0x8F_143
    MISS27-->|CONVERSATION|CONV_0x8E_142
    MISS27-->|CONVERSATION|CONV_0x8F_143
    MISS27-->|CONVERSATION|CONV_0x91_145
    MISS27-->|CONVERSATION|CONV_0x92_146
  end
  subgraph CONV28
    MISS28-->|CONVERSATION|CONV_0x9E_158
    MISS28-->|CONVERSATION|CONV_0x9F_159
    MISS28-->|CONVERSATION|CONV_0x94_148
    MISS28-->|CONVERSATION|CONV_0xE4_228
    MISS28-->|CONVERSATION|CONV_0xE8_232
    MISS28-->|CONVERSATION|CONV_0xEA_234
    MISS28-->|CONVERSATION|CONV_0xA2_162
    MISS28-->|CONVERSATION|CONV_0xE5_229
    MISS28-->|CONVERSATION|CONV_0xB7_183
    MISS28-->|CONVERSATION|CONV_0xE6_230
    MISS28-->|CONVERSATION|CONV_0xC7_199
    MISS28-->|CONVERSATION|CONV_0xE7_231
    MISS28-->|CONVERSATION|CONV_0xB4_180
    MISS28-->|CONVERSATION|CONV_0xB5_181
    MISS28-->|CONVERSATION|CONV_0xC4_196
    MISS28-->|CONVERSATION|CONV_0xC5_197
    MISS28-->|CONVERSATION|CONV_0x9A_154
    MISS28-->|CONVERSATION|CONV_0x9B_155
    MISS28-->|CONVERSATION|CONV_0x9C_156
    MISS28-->|CONVERSATION|CONV_0x08_8
    MISS28-->|CONVERSATION|CONV_0xA8_168
    MISS28-->|CONVERSATION|CONV_0xA9_169
    MISS28-->|CONVERSATION|CONV_0xAA_170
    MISS28-->|CONVERSATION|CONV_0x09_9
    MISS28-->|CONVERSATION|CONV_0xBC_188
    MISS28-->|CONVERSATION|CONV_0xBD_189
    MISS28-->|CONVERSATION|CONV_0xBE_190
    MISS28-->|CONVERSATION|CONV_0x05_5
    MISS28-->|CONVERSATION|CONV_0x03_3
    MISS28-->|CONVERSATION|CONV_0xA0_160
  end
  subgraph CONV29
    MISS29-->|CONVERSATION|CONV_0xA1_161
    MISS29-->|CONVERSATION|CONV_0x96_150
    MISS29-->|CONVERSATION|CONV_0x95_149
  end
  subgraph CONV30
    MISS30-->|CONVERSATION|CONV_0x97_151
  end
  subgraph CONV31
    MISS31-->|CONVERSATION|CONV_0x9D_157
    MISS31-->|CONVERSATION|CONV_0x98_152
    MISS31-->|CONVERSATION|CONV_0x99_153
  end
  subgraph CONV32
    MISS32-->|CONVERSATION|CONV_0xB6_182
    MISS32-->|CONVERSATION|CONV_0xEA_234
    MISS32-->|CONVERSATION|CONV_0xA3_163
    MISS32-->|CONVERSATION|CONV_0xA5_165
    MISS32-->|CONVERSATION|CONV_0xA4_164
  end
  subgraph CONV33
    MISS33-->|CONVERSATION|CONV_0xAC_172
    MISS33-->|CONVERSATION|CONV_0xAB_171
    MISS33-->|CONVERSATION|CONV_0xA6_166
    MISS33-->|CONVERSATION|CONV_0xA7_167
  end
  subgraph CONV34
    MISS34-->|CONVERSATION|CONV_0xAF_175
    MISS34-->|CONVERSATION|CONV_0xAD_173
    MISS34-->|CONVERSATION|CONV_0xAE_174
    MISS34-->|CONVERSATION|CONV_0xAD_173
    MISS34-->|CONVERSATION|CONV_0xAE_174
  end
  subgraph CONV35
    MISS35-->|CONVERSATION|CONV_0xB2_178
    MISS35-->|CONVERSATION|CONV_0xB3_179
    MISS35-->|CONVERSATION|CONV_0xB0_176
    MISS35-->|CONVERSATION|CONV_0xB1_177
  end
  subgraph CONV36
    MISS36-->|CONVERSATION|CONV_0xC6_198
    MISS36-->|CONVERSATION|CONV_0xEA_234
    MISS36-->|CONVERSATION|CONV_0xBA_186
    MISS36-->|CONVERSATION|CONV_0xB9_185
    MISS36-->|CONVERSATION|CONV_0xB8_184
  end
  subgraph CONV37
    MISS37-->|CONVERSATION|CONV_0xC0_192
    MISS37-->|CONVERSATION|CONV_0xBF_191
    MISS37-->|CONVERSATION|CONV_0xBB_187
  end
  subgraph CONV38
    MISS38-->|CONVERSATION|CONV_0xC3_195
    MISS38-->|CONVERSATION|CONV_0xC1_193
    MISS38-->|CONVERSATION|CONV_0xC2_194
    MISS38-->|CONVERSATION|CONV_0xC1_193
    MISS38-->|CONVERSATION|CONV_0xC2_194
  end

  subgraph CONV40
    MISS40-->|CONVERSATION|CONV_0xCA_202
    MISS40-->|CONVERSATION|CONV_0x9E_158
    MISS40-->|CONVERSATION|CONV_0x9F_159
    MISS40-->|CONVERSATION|CONV_0xC8_200
    MISS40-->|CONVERSATION|CONV_0xA2_162
    MISS40-->|CONVERSATION|CONV_0xE5_229
    MISS40-->|CONVERSATION|CONV_0xB7_183
    MISS40-->|CONVERSATION|CONV_0xE6_230
    MISS40-->|CONVERSATION|CONV_0xC7_199
    MISS40-->|CONVERSATION|CONV_0xE7_231
    MISS40-->|CONVERSATION|CONV_0xE8_232
    MISS40-->|CONVERSATION|CONV_0xEA_234
    MISS40-->|CONVERSATION|CONV_0xB4_180
    MISS40-->|CONVERSATION|CONV_0xB5_181
    MISS40-->|CONVERSATION|CONV_0xC4_196
    MISS40-->|CONVERSATION|CONV_0xC5_197
    MISS40-->|CONVERSATION|CONV_0xCB_203
    MISS40-->|CONVERSATION|CONV_0xCC_204
    MISS40-->|CONVERSATION|CONV_0xC9_201
  end
  subgraph CONV41
    MISS41-->|CONVERSATION|CONV_0xCD_205
    MISS41-->|CONVERSATION|CONV_0xCE_206
    MISS41-->|CONVERSATION|CONV_0xCF_207
    MISS41-->|CONVERSATION|CONV_0xD0_208
    MISS41-->|CONVERSATION|CONV_0xD1_209
    MISS41-->|CONVERSATION|CONV_0xD2_210
    MISS41-->|CONVERSATION|CONV_0xD0_208
    MISS41-->|CONVERSATION|CONV_0xD1_209
    MISS41-->|CONVERSATION|CONV_0xD3_211
  end
  subgraph CONV42
    MISS42-->|CONVERSATION|CONV_0xD7_215
    MISS42-->|CONVERSATION|CONV_0xD8_216
    MISS42-->|CONVERSATION|CONV_0xD9_217
    MISS42-->|CONVERSATION|CONV_0xD6_214
    MISS42-->|CONVERSATION|CONV_0xD5_213
    MISS42-->|CONVERSATION|CONV_0xD4_212
  end
  subgraph CONV43
    MISS43-->|CONVERSATION|CONV_0xDA_218
    MISS43-->|CONVERSATION|CONV_0xDB_219
  end

  subgraph CONV45
    MISS45-->|CONVERSATION|CONV_0xDD_221
    MISS45-->|CONVERSATION|CONV_0xDE_222
    MISS45-->|CONVERSATION|CONV_0xDC_220
    MISS45-->|CONVERSATION|CONV_0xE0_224
    MISS45-->|CONVERSATION|CONV_0xE1_225
    MISS45-->|CONVERSATION|CONV_0xDF_223
  end

  subgraph CONV47
    MISS47-->|CONVERSATION|CONV_0xE3_227
    MISS47-->|CONVERSATION|CONV_0xE2_226
  end
  subgraph CONV48
    MISS48-->|CONVERSATION|CONV_0xEC_236
  end

  classDef missClass fill:#f96, stroke:#333, stroke-width:2px;
  classDef flyClass fill:#9cf, stroke:#333, stroke-width:1px;
  
  %% Application des styles aux nœuds
  class MISS0,MISS1,MISS2,MISS3,MISS4,MISS5,MISS6,MISS7,MISS8,MISS9,MISS10,MISS11,MISS12,MISS13,MISS14,MISS15,MISS16,MISS17,MISS18,MISS19,MISS20,MISS21,MISS22,MISS23,MISS24,MISS25,MISS26,MISS27,MISS28,MISS29,MISS30,MISS31,MISS32,MISS33,MISS34,MISS35,MISS36,MISS37,MISS38,MISS39,MISS40,MISS41,MISS42,MISS43,MISS44,MISS45,MISS46,MISS47,MISS48 missClass;
  class FLY_0x00_0,FLY_0x01_1,FLY_0x02_2,FLY_0x03_3,FLY_0x04_4,FLY_0x05_5,FLY_0x06_6,FLY_0x07_7,FLY_0x08_8,FLY_0x09_9,FLY_0x0B_11,FLY_0x0C_12,FLY_0x0D_13,FLY_0x0E_14,FLY_0x0F_15,FLY_0x10_16,FLY_0x11_17,FLY_0x12_18,FLY_0x13_19,FLY_0x14_20,FLY_0x15_21,FLY_0x16_22,FLY_0x17_23,FLY_0x18_24,FLY_0x19_25,FLY_0x1A_26,FLY_0x1B_27,FLY_0x1C_28,FLY_0x1D_29,FLY_0x1E_30,FLY_0x1F_31,FLY_0x20_32,FLY_0x21_33,FLY_0x22_34,FLY_0x23_35,FLY_0x24_36,FLY_0x25_37,FLY_0x26_38,FLY_0x27_39,FLY_0x2B_43,FLY_0x2C_44,FLY_0x2D_45,FLY_0x2E_46 flyClass;
