flowchart LR
  MISS0
    MISS0-->|GO TO|MISS1
  MISS1
    MISS1-->|GO TO|MISS2
  MISS2
    MISS2-->|GO TO|MISS2
    MISS2-->|GO TO|MISS3
  MISS3
    MISS3-->|GO TO|MISS4
  MISS4
    MISS4-->|GO TO|MISS5
  MISS5
    MISS5-->|GO TO|MISS6
  MISS6
    MISS6-->|GO TO|MISS7
  MISS7
    MISS7-->|GO TO|MISS8
  MISS8
    MISS8-->|GO TO|MISS9
    MISS8-->|GO TO|MISS8
  MISS9
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS21
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS10
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS10
    MISS9-->|GO TO|MISS13
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS13
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS17
    MISS9-->|GO TO|MISS9
    MISS9-->|GO TO|MISS17
    MISS9-->|GO TO|MISS9
  MISS10
    MISS10-->|GO TO|MISS11
  MISS11
    MISS11-->|GO TO|MISS12
  MISS12
    MISS12-->|GO TO|MISS12
    MISS12-->|GO TO|MISS9
    MISS12-->|GO TO|MISS21
  MISS13
    MISS13-->|GO TO|MISS14
  MISS14
    MISS14-->|GO TO|MISS15
  MISS15
    MISS15-->|GO TO|MISS16
  MISS16
    MISS16-->|GO TO|MISS16
    MISS16-->|GO TO|MISS9
    MISS16-->|GO TO|MISS21
  MISS17
    MISS17-->|GO TO|MISS18
  MISS18
    MISS18-->|GO TO|MISS19
  MISS19
    MISS19-->|GO TO|MISS20
  MISS20
    MISS20-->|GO TO|MISS20
    MISS20-->|GO TO|MISS9
    MISS20-->|GO TO|MISS21
  MISS21
    MISS21-->|GO TO|MISS22
  MISS22
    MISS22-->|GO TO|MISS23
  MISS23
    MISS23-->|GO TO|MISS24
  MISS24
    MISS24-->|GO TO|MISS24
    MISS24-->|GO TO|MISS25
  MISS25
    MISS25-->|GO TO|MISS26
  MISS26
    MISS26-->|GO TO|MISS27
  MISS27
    MISS27-->|GO TO|MISS27
    MISS27-->|GO TO|MISS28
    MISS27-->|GO TO|MISS28
    MISS27-->|GO TO|MISS28
  MISS28
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS39
    MISS28-->|GO TO|MISS29
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS29
    MISS28-->|GO TO|MISS32
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS32
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS36
    MISS28-->|GO TO|MISS28
    MISS28-->|GO TO|MISS36
    MISS28-->|GO TO|MISS28
  MISS29
    MISS29-->|GO TO|MISS30
  MISS30
    MISS30-->|GO TO|MISS31
  MISS31
    MISS31-->|GO TO|MISS31
    MISS31-->|GO TO|MISS28
    MISS31-->|GO TO|MISS39
  MISS32
    MISS32-->|GO TO|MISS33
  MISS33
    MISS33-->|GO TO|MISS34
  MISS34
    MISS34-->|GO TO|MISS35
  MISS35
    MISS35-->|GO TO|MISS35
    MISS35-->|GO TO|MISS28
    MISS35-->|GO TO|MISS39
  MISS36
    MISS36-->|GO TO|MISS37
  MISS37
    MISS37-->|GO TO|MISS38
  MISS38
    MISS38-->|GO TO|MISS38
    MISS38-->|GO TO|MISS28
    MISS38-->|GO TO|MISS39
  MISS39
    MISS39-->|GO TO|MISS40
  MISS40
    MISS40-->|GO TO|MISS41
  MISS41
    MISS41-->|GO TO|MISS41
    MISS41-->|GO TO|MISS42
    MISS41-->|GO TO|MISS42
  MISS42
    MISS42-->|GO TO|MISS43
  MISS43
    MISS43-->|GO TO|MISS44
  MISS44
    MISS44-->|GO TO|MISS45
  MISS45
    MISS45-->|GO TO|MISS46
  MISS46
    MISS46-->|GO TO|MISS47
  MISS47
    MISS47-->|GO TO|MISS48
  MISS48

  subgraph M0
    direction TB
    MISS0-->|FLY MISSION|FLY_0x00_0
  end
  subgraph M1
    direction TB
    MISS1-->|FLY MISSION|FLY_0x01_1
  end
  subgraph M2
    direction TB
    MISS2-->|FLY MISSION|FLY_0x02_2
  end
  subgraph M4
    direction TB
    MISS4-->|FLY MISSION|FLY_0x03_3
  end
  subgraph M6
    direction TB
    MISS6-->|FLY MISSION|FLY_0x04_4
  end
  subgraph M7
    direction TB
    MISS7-->|FLY MISSION|FLY_0x05_5
  end
  subgraph M8
    direction TB
    MISS8-->|FLY MISSION|FLY_0x06_6
  end
  subgraph M10
    direction TB
    MISS10-->|FLY MISSION|FLY_0x07_7
  end
  subgraph M11
    direction TB
    MISS11-->|FLY MISSION|FLY_0x08_8
  end
  subgraph M12
    direction TB
    MISS12-->|FLY MISSION|FLY_0x09_9
  end
  subgraph M14
    direction TB
    MISS14-->|FLY MISSION|FLY_0x0B_11
  end
  subgraph M15
    direction TB
    MISS15-->|FLY MISSION|FLY_0x0C_12
  end
  subgraph M16
    direction TB
    MISS16-->|FLY MISSION|FLY_0x0D_13
  end
  subgraph M17
    direction TB
    MISS17-->|FLY MISSION|FLY_0x0E_14
  end
  subgraph M18
    direction TB
    MISS18-->|FLY MISSION|FLY_0x0F_15
    MISS18-->|FLY MISSION|FLY_0x2B_43
  end
  subgraph M19
    direction TB
    MISS19-->|FLY MISSION|FLY_0x10_16
  end
  subgraph M20
    direction TB
    MISS20-->|FLY MISSION|FLY_0x11_17
  end
  subgraph M21
    direction TB
    MISS21-->|FLY MISSION|FLY_0x12_18
  end
  subgraph M22
    direction TB
    MISS22-->|FLY MISSION|FLY_0x13_19
  end
  subgraph M23
    direction TB
    MISS23-->|FLY MISSION|FLY_0x14_20
    MISS23-->|FLY MISSION|FLY_0x14_20
  end
  subgraph M24
    direction TB
    MISS24-->|FLY MISSION|FLY_0x15_21
  end
  subgraph M25
    direction TB
    MISS25-->|FLY MISSION|FLY_0x16_22
  end
  subgraph M26
    direction TB
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
    MISS26-->|FLY MISSION|FLY_0x17_23
    MISS26-->|FLY MISSION|FLY_0x2C_44
  end
  subgraph M27
    direction TB
    MISS27-->|FLY MISSION|FLY_0x18_24
  end
  subgraph M29
    direction TB
    MISS29-->|FLY MISSION|FLY_0x19_25
  end
  subgraph M30
    direction TB
    MISS30-->|FLY MISSION|FLY_0x1A_26
  end
  subgraph M31
    direction TB
    MISS31-->|FLY MISSION|FLY_0x1B_27
  end
  subgraph M32
    direction TB
    MISS32-->|FLY MISSION|FLY_0x1C_28
  end
  subgraph M33
    direction TB
    MISS33-->|FLY MISSION|FLY_0x1D_29
    MISS33-->|FLY MISSION|FLY_0x2D_45
  end
  subgraph M34
    direction TB
    MISS34-->|FLY MISSION|FLY_0x1E_30
  end
  subgraph M35
    direction TB
    MISS35-->|FLY MISSION|FLY_0x1F_31
  end
  subgraph M36
    direction TB
    MISS36-->|FLY MISSION|FLY_0x20_32
  end
  subgraph M37
    direction TB
    MISS37-->|FLY MISSION|FLY_0x21_33
    MISS37-->|FLY MISSION|FLY_0x2E_46
  end
  subgraph M38
    direction TB
    MISS38-->|FLY MISSION|FLY_0x22_34
  end
  subgraph M40
    direction TB
    MISS40-->|FLY MISSION|FLY_0x23_35
  end
  subgraph M41
    direction TB
    MISS41-->|FLY MISSION|FLY_0x24_36
  end
  subgraph M42
    direction TB
    MISS42-->|FLY MISSION|FLY_0x25_37
  end
  subgraph M43
    direction TB
    MISS43-->|FLY MISSION|FLY_0x26_38
  end
  subgraph M45
    direction TB
    MISS45-->|FLY MISSION|FLY_0x27_39
  end


  %% Définition des styles pour différencier MISS et FLY
  classDef missClass fill:#f96, stroke:#333, stroke-width:2px;
  classDef flyClass fill:#9cf, stroke:#333, stroke-width:1px;
  
  %% Application des styles aux nœuds
  class MISS0,MISS1,MISS2,MISS3,MISS4,MISS5,MISS6,MISS7,MISS8,MISS9,MISS10,MISS11,MISS12,MISS13,MISS14,MISS15,MISS16,MISS17,MISS18,MISS19,MISS20,MISS21,MISS22,MISS23,MISS24,MISS25,MISS26,MISS27,MISS28,MISS29,MISS30,MISS31,MISS32,MISS33,MISS34,MISS35,MISS36,MISS37,MISS38,MISS39,MISS40,MISS41,MISS42,MISS43,MISS44,MISS45,MISS46,MISS47,MISS48 missClass;
  class FLY_0x00_0,FLY_0x01_1,FLY_0x02_2,FLY_0x03_3,FLY_0x04_4,FLY_0x05_5,FLY_0x06_6,FLY_0x07_7,FLY_0x08_8,FLY_0x09_9,FLY_0x0B_11,FLY_0x0C_12,FLY_0x0D_13,FLY_0x0E_14,FLY_0x0F_15,FLY_0x10_16,FLY_0x11_17,FLY_0x12_18,FLY_0x13_19,FLY_0x14_20,FLY_0x15_21,FLY_0x16_22,FLY_0x17_23,FLY_0x18_24,FLY_0x19_25,FLY_0x1A_26,FLY_0x1B_27,FLY_0x1C_28,FLY_0x1D_29,FLY_0x1E_30,FLY_0x1F_31,FLY_0x20_32,FLY_0x21_33,FLY_0x22_34,FLY_0x23_35,FLY_0x24_36,FLY_0x25_37,FLY_0x26_38,FLY_0x27_39,FLY_0x2B_43,FLY_0x2C_44,FLY_0x2D_45,FLY_0x2E_46 flyClass;